### ISSUE TITLE
Manually committed transactions issue rollback on Connection.close()

### ISSUE THREAD

**Issue by arunim29** [r2dbc/r2dbc-pool#23]
Hi,
In class https://github.com/r2dbc/r2dbc-pool/blob/master/src/main/java/io/r2dbc/pool/PooledConnection.java, we can see that in close() method, if auto-commit is false, the transaction is always rollbacked before releasing the connection back to the pool. Because of this, if I write 
connection.commit().then(connection.close()), it throws an exception.

**Comment by mp911de** [comment]
We should improve the control to perform only a rollback when a transaction was left active.

Please note that R2DBC Connections do not have explicit controls for auto-commit mode yet (see r2dbc/r2dbc-spi#95)

**Comment by mp911de** [comment]
That's fixed now. Care to retest with latest 0.8.0 snapshots? (`r2dbc-pool-0.8.0.BUILD-20190720.154444-1.jar`)

**Comment by arunim29** [comment]
where to get this jar from?

**Comment by mp911de** [comment]
Take a look [here](https://repo.spring.io/snapshot/io/r2dbc/r2dbc-pool/0.8.0.BUILD-SNAPSHOT/r2dbc-pool-0.8.0.BUILD-20190720.154452-25.jar). When using Maven, point a repository entry to https://repo.spring.io/snapshot/.

**Comment by arunim29** [comment]
An exception is coming using the jar given above-:
Exception in thread "main" java.lang.NoClassDefFoundError: reactor/pool/PoolMetricsRecorder
	at io.r2dbc.pool.ConnectionPoolConfiguration.builder(ConnectionPoolConfiguration.java:87)
	at io.r2dbc.pool.PoolingConnectionFactoryProvider.create(PoolingConnectionFactoryProvider.java:88)
	at io.r2dbc.pool.PoolingConnectionFactoryProvider.create(PoolingConnectionFactoryProvider.java:34)
	at io.r2dbc.spi.ConnectionFactories.find(ConnectionFactories.java:44)
	at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:74)

**Comment by arunim29** [comment]
@mp911de I am using r2dbc-pool version **0.8.0.BUILD-20190720.154452-25** and r2dbc-mssql version **0.8.0.BUILD-20190722.125320-25**. But I am still getting the error as follows -:

 io.r2dbc.mssql.ExceptionFactory$MssqlNonTransientException: The server failed to resume the transaction. Desc:6900000001.

I have observed that this error comes only when I use createStatement().bind(something). If I use createStatement() without any binding, I get no exception.

Please resolve the issue.

**Comment by mp911de** [comment]
Can you please provide a reproducer?

**Comment by arunim29** [comment]
`package com.test;

import java.time.Duration;
import java.util.function.Function;

import io.r2dbc.pool.ConnectionPool;
import io.r2dbc.pool.ConnectionPoolConfiguration;
import io.r2dbc.spi.Connection;
import io.r2dbc.spi.ConnectionFactories;
import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.ConnectionFactoryOptions;
import reactor.core.publisher.Mono;

public class Sample5 {
	
	public static void main(String[] args) {
		ConnectionFactory connectionFactory = ConnectionFactories.get(ConnectionFactoryOptions.builder()
				.option(ConnectionFactoryOptions.DRIVER, "pool").option(ConnectionFactoryOptions.PROTOCOL, "mssql")
				.option(ConnectionFactoryOptions.HOST, "host") 
				.option(ConnectionFactoryOptions.USER, "user") 
				.option(ConnectionFactoryOptions.PASSWORD, "password") 
				.option(ConnectionFactoryOptions.DATABASE, "database") 
				.option(ConnectionFactoryOptions.PORT, port) 
				.build());

		ConnectionPoolConfiguration configuration = ConnectionPoolConfiguration.builder(connectionFactory)
				.validationQuery("SELECT 1").maxIdleTime(Duration.ofMillis(1000)) 
				.maxSize(20) 
				.build();

		ConnectionPool pool = new ConnectionPool(configuration);
		
		Mono<Connection> resourceProvider = pool.create();

		Function<Connection, Mono<Integer>> resourceClosure = new Function<Connection, Mono<Integer>>() {

			@Override
			public Mono<Integer> apply(Connection connection) {
				Mono<Integer> mono = Mono.just(connection).map(obj -> {
					return connection.createStatement("any update query");  //no error
					//return connection.createStatement("any update query").bind(index, value); //error
				}).flatMap(stmt -> {
					return Mono.from(stmt.execute());
				}).flatMap(result -> {
					return Mono.from(result.getRowsUpdated());
				}).doOnError(ex -> {
					ex.printStackTrace();
				});
				return Mono.from(connection.beginTransaction()).then(mono);
			}
		};
		
		Function<Connection, Mono<Void>> asyncCleanup = new Function<Connection, Mono<Void>>() {

			@Override
			public Mono<Void> apply(Connection connection) {
				//Mono<Void> commitMono = Mono.from(connection.commitTransaction());
				Mono<Void> closeMono = Mono.from(connection.close());
				return closeMono;
			}
		};

		/**
		 *  Function returning a mono which runs resource cleanup if resourceClosure terminates with onError
		 */
		Function<Connection, Mono<Void>> asyncCleanupOnError = new Function<Connection, Mono<Void>>() {

			@Override
			public Mono<Void> apply(Connection connection) {
				//Mono<Void> rollbackMono = Mono.from(connection.rollbackTransaction());
				Mono<Void> closeMono = Mono.from(connection.close());
				return closeMono;
			}
		};
		
		Mono<Integer> updatedRows = Mono.usingWhen(resourceProvider, resourceClosure, asyncCleanup, asyncCleanupOnError);
		
		updatedRows.doOnNext(i -> {
			System.out.println("updated rows " + i);
		}).subscribe();
		
	}

}
`

**Comment by mp911de** [comment]
The issue you're observing is a bug in the SQL Server driver, see r2dbc/r2dbc-mssql#84.

**Comment by arunim29** [comment]
as  [r2dbc/r2dbc-mssql#84.](url) is closed, has the bug been resolved there?

**Comment by mp911de** [comment]
Yes, it has.

**Comment by arunim29** [comment]
Hi @mp911de , I tested the code with latest snapshots of both r2dbc-mssql and r2dbc-pool dated 24th July. The issue is fixed in those snapshots. Thank you very much.
Can you give an estimate when these builds will be promoted to spring milestones?

**Comment by mp911de** [comment]
I don't have a date yet. Keep watching the [0.8.0 RC1 milestone or repo](https://github.com/r2dbc/r2dbc-mssql/milestone/3), I expect something around October timeframe.
